"""Emit reference outputs from the Python engine for the JS port to match.

The browser engine is a second implementation of the same model. Two
implementations drift; the only defence is a fixture set generated by the one
that owns the maths and asserted by the other.

Deterministic quantities are compared exactly (to 1e-9). The true-count
simulation uses a different generator in each language, so that one is compared
statistically instead -- see web/tests/conformance.test.mjs.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from bjtoolkit.analyzer import (  # noqa: E402
    action_evs,
    dealer_outcomes,
    prob_dealer_blackjack,
)
from bjtoolkit.cards import ACE, RANK_NAMES, TEN, fresh_deck, remove_many  # noqa: E402
from bjtoolkit.ramp import spread_ramp  # noqa: E402
from bjtoolkit.risk import (  # noqa: E402
    bankroll_for_ror,
    evaluate,
    kelly_for_ror,
    ror_for_kelly,
)
from bjtoolkit.rules import (  # noqa: E402
    PRESETS,
    base_edge,
    base_edge_range,
    get_preset,
)
from bjtoolkit.strategy import basic_strategy, insurance_index  # noqa: E402

CHART_PRESETS = ("vegas-strip", "ambassador", "vegas-h17", "single-deck")


def fixtures() -> dict:
    out: dict = {"edges": {}, "dealer": {}, "charts": {}, "actionEvs": [],
                 "insurance": {}, "risk": {}}

    for name in PRESETS:
        r = get_preset(name)
        lo, hi = base_edge_range(r)
        out["edges"][name] = {"edge": base_edge(r), "low": lo, "high": hi}

    for decks in (1, 2, 6, 8):
        deck = fresh_deck(decks)
        for h17 in (False, True):
            for up in range(10):
                key = f"{decks}|{int(h17)}|{up}"
                out["dealer"][key] = list(
                    dealer_outcomes(up, remove_many(deck, up), h17, True)
                )

    for name in CHART_PRESETS:
        r = get_preset(name)
        out["charts"][name] = {
            f"{c.category}|{c.label}|{RANK_NAMES[c.upcard]}": c.action.value
            for c in basic_strategy(r)
        }
        out["insurance"][name] = insurance_index(r)

    # A handful of exact action EVs, chosen to exercise the branches that
    # matter: the ENHC blackjack term, splits with resplits, and surrender.
    probes = [
        ("ambassador", (3, 4), ACE),      # 11 vs A, full ENHC
        ("ambassador", (3, 4), TEN),      # 11 vs T, the fifth correction
        ("ambassador", (6, 6), TEN),      # 8,8 vs T -> surrender
        ("ambassador", (ACE, ACE), ACE),  # A,A vs A -> hit
        ("vegas-strip", (3, 4), ACE),
        ("vegas-strip", (6, 6), 7),
        ("vegas-strip", (4, 8), 7),       # T,6 vs 9, the composition case
        ("vegas-h17", (7, 7), 4),
        ("single-deck", (0, 0), 5),
    ]
    for preset, cards, up in probes:
        r = get_preset(preset)
        deck = remove_many(fresh_deck(r.decks), *cards, up)
        evs = action_evs(cards, up, deck, r)
        out["actionEvs"].append({
            "preset": preset, "cards": list(cards), "upcard": up,
            "pBlackjack": prob_dealer_blackjack(up, deck),
            "evs": {a.value: v for a, v in evs.items()},
        })

    # Risk arithmetic against a fixed frequency table, so the comparison does
    # not depend on either language's shuffler.
    freq = {-3: 0.04, -2: 0.07, -1: 0.13, 0: 0.40, 1: 0.13,
            2: 0.085, 3: 0.055, 4: 0.035, 5: 0.02, 6: 0.015}
    total = sum(freq.values())
    freq = {k: v / total for k, v in freq.items()}
    out["risk"]["freq"] = {str(k): v for k, v in freq.items()}

    class FixedDist:
        def __init__(self, probs):
            self.probs = probs

        def counts(self):
            return sorted(self.probs)

        def p(self, tc):
            return self.probs.get(tc, 0.0)

    dist = FixedDist(freq)
    rows = []
    for preset in ("ambassador", "vegas-strip"):
        r = get_preset(preset)
        for spread in (4, 8, 16):
            for wong in (None, 1):
                ramp = spread_ramp(r, dist, max_spread=spread,
                                   unit=r.table_min, wong_out_below=wong)
                rep = evaluate(r, dist, ramp, bankroll=100_000)
                rows.append({
                    "preset": preset, "spread": spread, "wong": wong,
                    "bets": {str(k): v for k, v in ramp.bets.items()},
                    "winRatePerRound": rep.win_rate_per_round,
                    "variancePerRound": rep.variance_per_round,
                    "n0Rounds": rep.n0_rounds,
                    "riskOfRuin": rep.risk_of_ruin,
                    "probOfProfit": rep.prob_of_profit,
                    "requiredBankroll": bankroll_for_ror(
                        0.05, rep.win_rate_per_round, rep.variance_per_round
                    ),
                })
    out["risk"]["cases"] = rows
    out["risk"]["kellyForRor"] = {str(t): kelly_for_ror(t)
                                  for t in (0.01, 0.05, 0.1, 0.25)}
    out["risk"]["rorForKelly"] = {str(f): ror_for_kelly(f)
                                  for f in (0.2, 0.4, 0.5, 1.0)}
    return out


def main() -> int:
    path = ROOT / "tests" / "fixtures" / "conformance.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(fixtures(), indent=1, sort_keys=True))
    size = path.stat().st_size / 1024
    print(f"wrote {path} ({size:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
